### PR TITLE
Prac 3 - GPS code review request

### PR DESCRIPTION
**Pull request by maheshram-hs**
Something feels/is wrong about the calculation and logic behind the GPS (Gopher Population Simulator) program, please help me fix it. @TanishiJain

### CODE REVIEW

**Comment by erza963** [comment]
its looks fine

**Comment by erza963** [comment]
check your email of this morning

**Comment by maheshram-hs** [comment]
Thank you.

**Comment by erza963** [comment]
check your email again

**Comment by maheshram-hs** [comment]
Please don't use this to communicate off-topic subjects.

**Comment by erza963** [comment]
ok

**Pull request merged**
